apiVersion: apps/v1
kind: Deployment
metadata:
  name: akswebapp
  labels:
    app: akswebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akswebapp
  template:
    metadata:
      labels:
        app: akswebapp
    spec:
      containers:
      - name: sample-app
        image: akslearning01.azurecr.io/akswebapp:version1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: akswebapp
spec:
  selector:
    app: akswebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
